### ISSUE TITLE
CUDA Out of Memory

### ISSUE THREAD

**Issue by YuWang24** [gyhui14/spottune#3]
Hi Dr Guo
I was trying to run your code simply on one dataset, the aircraft dataset. However, I encountered a CUDA out of Memory issue. I am trying to run the code on my laptop, the GPU I have is not a high-grade one, only MX150. But I think it should be able to handle the case when only one dataset is loaded. What might be the cause for such a problem? Any explanation or guidance will be much appreciated. Thanks in advance.

**Comment by gyhui14** [comment]
Hi YuWang24, how large is your GPU memory?

**Comment by YuWang24** [comment]
> Hi YuWang24, how large is your GPU memory?

Thanks for the reply. The GPU of my laptop is MX150, and it has a memory of 2GB. Would this be sufficient for training?

**Comment by gyhui14** [comment]
Hi YuWang24, that is too small to run the model.

**Comment by YuWang24** [comment]
> Hi YuWang24, that is too small to run the model.

Thanks for the explanation Dr Guo. Then I will try to run this model on my desktop later. Will a GTX1060 with 6GB memory be sufficient for this model?

**Comment by gyhui14** [comment]
I use 2 TiTan Xp with 12GB each. However, you can try to reduce the batch size.

**Comment by YuWang24** [comment]
> I use 2 TiTan Xp with 12GB each. However, you can try to reduce the batch size.

Okay, I will try to reduce the batch size to see whether it can run or not. Thanks again Dr Guo, I will close this issue.
